# fly.toml app configuration file generated for golf-tip-app on 2025-08-05T08:12:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'golf-tip-app'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/release'

[env]
  PORT = '8080'  # Rails/Puma listens on 8080 (non-privileged port)

[[mounts]]
  source = 'data'
  destination = '/rails/storage'
  processes = ['app']

[http_service]
  internal_port = 8080  # Fly.io proxy connects to Puma on 8080
  force_https = true
  auto_stop_machines = 'suspend'  # Suspend instead of stop (faster restarts)
  auto_start_machines = true
  min_machines_running = 1  # Keep 1 machine running to avoid cold starts
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'  # Less frequent checks
    timeout = '10s'    # Increased timeout for slow responses
    grace_period = '60s'  # More time for startup
    method = 'GET'
    path = '/up'  # Health check hits Thruster on port 80

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'  # Increased to 1GB for better performance and headroom
  cpu_kind = 'shared'
  cpus = 1
